import { DerivSymbol } from '../types/trading';

export const DERIV_SYMBOLS: DerivSymbol[] = [
  // Volatility Indices (Standard)
  {
    symbol: 'R_25',
    displayName: 'Volatility 25 Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 3,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1850.5,
  },
  {
    symbol: 'R_10',
    displayName: 'Volatility 10 Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 3,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 7520.0,
  },
  {
    symbol: 'R_50',
    displayName: 'Volatility 50 Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 4,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 345.2,
  },
  {
    symbol: 'R_75',
    displayName: 'Volatility 75 Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 4,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1450.8,
  },
  {
    symbol: 'R_100',
    displayName: 'Volatility 100 Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1120.4,
  },
  // 1-Second Indices
  {
    symbol: '1HZ10V',
    displayName: 'Volatility 10 (1s) Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 7420.25,
  },
  {
    symbol: '1HZ25V',
    displayName: 'Volatility 25 (1s) Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1250.6,
  },
  {
    symbol: '1HZ50V',
    displayName: 'Volatility 50 (1s) Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 350.15,
  },
  {
    symbol: '1HZ75V',
    displayName: 'Volatility 75 (1s) Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1450.4,
  },
  {
    symbol: '1HZ100V',
    displayName: 'Volatility 100 (1s) Index',
    market: 'synthetic_index',
    submarket: 'random_index',
    decimals: 2,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 3240.8,
  },
  // Step & Crash / Boom
  {
    symbol: 'stpRNG',
    displayName: 'Step Index',
    market: 'synthetic_index',
    submarket: 'step_index',
    decimals: 1,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 12500.0,
  },
  {
    symbol: 'BOOM500',
    displayName: 'Boom 500 Index',
    market: 'synthetic_index',
    submarket: 'crash_boom',
    decimals: 4,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 4850.5,
  },
  {
    symbol: 'CRASH500',
    displayName: 'Crash 500 Index',
    market: 'synthetic_index',
    submarket: 'crash_boom',
    decimals: 4,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 5150.2,
  },
  // Major Forex
  {
    symbol: 'frxEURUSD',
    displayName: 'EUR/USD',
    market: 'forex',
    submarket: 'major_pairs',
    decimals: 5,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1.0852,
  },
  {
    symbol: 'frxGBPUSD',
    displayName: 'GBP/USD',
    market: 'forex',
    submarket: 'major_pairs',
    decimals: 5,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 1.2945,
  },
  {
    symbol: 'frxUSDJPY',
    displayName: 'USD/JPY',
    market: 'forex',
    submarket: 'major_pairs',
    decimals: 3,
    minDuration: 5,
    maxDuration: 60,
    defaultBasePrice: 154.65,
  },
];

export function getSymbolDetails(symbol: string): DerivSymbol {
  return (
    DERIV_SYMBOLS.find((s) => s.symbol === symbol) || {
      symbol,
      displayName: symbol,
      market: 'synthetic_index',
      submarket: 'random_index',
      decimals: 3,
      minDuration: 5,
      maxDuration: 60,
    }
  );
}
